### ISSUE TITLE
Interfaz jefe de taller

### ISSUE THREAD

**Issue by Shinku24** [Valeriarm/ProyectoDesarrollo#60]
- Id de orden se genera automáticamente
- Al abrir la interfaz se muestran cosas que deben estar ocultas
- Hacer un Tooltiptext para indicar que se le debe dar botón izq
- En algunas de los botones no desaparecen/aparecen los campos completamente 
- Id del jefe de taller no e necesario
- La fecha en el formato de la interfaz del super (con combobox)?
- Utilidad del checkbox "es Cliente"?
- Revisar en la carpetas de imágenes para usarlas según el caso
- El botón "agregar" no se ubica bien, revisar si está en el jpanel correcto

**Comment by Marthox1999** [comment]
Solved, please review the corrections and aprove it

**Comment by Marthox1999** [comment]
Solved, please review the corrections and aprove it

**Comment by Shinku24** [comment]
//Los números corresponden a los asteriscos del comentario inicial del issue
1. Se podría colocar SERIAL en el id de la base de datos y no calcularlo
2. Terminado
3. No está hecho
4. En este caso hay que revisar con las HU (creo que faltan algunos atributos), también revisar el el 6to asterisco
5. Terminado
6. Terminado
7. Terminado (ya fue removido)
8. Falta las espc (esto fue petición de mateo)
9. Revisar el segundo asterisco de abajo

//Otros detalles a revisar
* El label de valorUnitario esta más arriba hay que acomodarlo directamente en design
* El botón esta desacomodado (más a la der) en vez de estar centrado, se podría revisar los layout o mirar la ubicación actual del botón en design
* En modificar (de inventario) en textfield de lote está deshabilitado, en caso de que no se pueda modf entonces está bien
* En modificar (de inventario) es correcto decir id del producto? cuando lo que se guarda es el lote como tal?
* El testfield de Id Producto en consultar y anular (de inventario) se hace pequeño,se puede arreglar cambiando el 'preferred size' por el que tiene actualmente en desing (que es de 152 en horizontal) y luego quitarle el 'Horizontal resizable' en propiedades del textfield
* Los combobox de fecha aparecen en consultar y anular (de orden)
* El textfield (de orden) de 'nombre de producto' acepta caracteres distintos a letras
* Los textfield (de orden) 'id producto', 'id cliente', 'telefono' y 'costo' aceptan caracteres distintos a numeros (a menos que el id pueda tener letras)
* El textfield (de inventario) de 'nombre de producto' acepta caracteres distintos a letras 
* Los textfield (de orden) 'lote', 'valor unitario', 'cantidad lote' aceptan caracteres distintos a numeros
** PARA los 4 asteriscos anteriores tener en cuenta los textfield que son compartidos
* El textfield de 'telefono' no permite que sea multivalorado(en caso de que este lo sea)
* Hay que comprobar que cada función este correctamente conectada a la base de datos, probar las funciones

**Comment by Shinku24** [comment]
1. Id de orden se genera automáticamente
3. Hacer un Tooltiptext para indicar que se le debe dar botón izq
8. Revisar en la carpetas de imágenes para usarlas según el caso
9. El botón "agregar" no se ubica bien, revisar si está en el jpanel correcto

//Observacion   o(observacion)-#(numero)
O-1. Al final como se dejo lo de la id de orden?
O-3. En este caso hay que acomodarlo al nuevo diseño si es aprobado, pero falta el diseño, así que **Terminado**
O-8. **Terminado** (falta ver si se cambia la interfaz)
O-9. **Terminado**


//Para los otros detalles
*El label de valorUnitario esta más arriba hay que acomodarlo directamente en design
O. **Terminado**

*El botón esta desacomodado (más a la der) en vez de estar centrado, se podría revisar los layout o mirar la ubicación actual del botón en design
O. **Terminado**

*En modificar (de inventario) en textfield de lote está deshabilitado, en caso de que no se pueda modf entonces está bien
O. Segun la observacion previa, entonces este campo no se modifica. **Terminado**

*En modificar (de inventario) es correcto decir id del producto? cuando lo que se guarda es el lote como tal?
O. **Terminado**

*El textfield* de Id Producto en consultar y anular (de inventario) se hace pequeño,se puede arreglar cambiando el 'preferred size' por el que tiene actualmente en desing (que es de 152 en horizontal) y luego quitarle el 'Horizontal resizable' en propiedades del textfield
O. **Terminado**

*Los combobox de fecha aparecen en consultar y anular (de orden)
O. **Terminado**

*El textfield (de orden) de 'nombre de producto' acepta caracteres distintos a letras
O. **NO Terminado**

*Los textfield (de orden) 'id producto', 'id cliente', 'telefono' y 'costo' aceptan caracteres distintos a numeros (a menos que el id pueda tener letras)
O. **NO Terminado**

*El textfield (de inventario) de 'nombre de producto' acepta caracteres distintos a letras
O. **NO Terminado**

*Los textfield (de inventario*) 'lote', 'valor unitario', 'cantidad lote' aceptan caracteres distintos a numeros
O. **NO Terminado**

** PARA los 4 asteriscos anteriores tener en cuenta los textfield que son compartidos
O. Solo es una ayuda

*El textfield de 'telefono' no permite que sea multivalorado(en caso de que este lo sea)
O. **No se Ha definido si telefono es multivalorado**

*Hay que comprobar que cada función este correctamente conectada a la base de datos, probar las funciones
O. Al parecer esta en **'NO Terminado'** (se probó con agregar inventario)

**Comment by Shinku24** [comment]
**CAMBIOS ANTERIORES POR HACER**			
* La id de orden se puso SERIAL?
1. El textfield (de orden) de 'nombre de producto' acepta caracteres distintos a letras
2. Los textfield (de orden) 'id producto', 'id cliente', 'telefono' y 'costo' aceptan caracteres distintos a numeros (a menos que el id pueda tener letras)
3. El textfield (de inventario) de 'nombre de producto' acepta caracteres distintos a letras
4. Los textfield (de inventario*) 'lote', 'valor unitario', 'cantidad lote' aceptan caracteres distintos a numeros

5. El textfield de 'telefono' no permite que sea multivalorado(en caso de que este lo sea)
O. **No se Ha definido si telefono es multivalorado**

6. Hay que comprobar que cada función este correctamente conectada a la base de datos, probar las funciones
O. Al parecer esta en **'NO Terminado'** (se probó con agregar inventario)



**Nuevos Observaciones encontradas**
7. Fecha y hora (abajo en la interfaz) no aparecen
8. No todos los campos se limpian al cambiar entre opciones
