### ISSUE TITLE
Pregunta: SuperUsuario (sedes)

### ISSUE THREAD

**Issue by Shinku24** [Valeriarm/ProyectoDesarrollo#61]
Consideran que según la forma en que se está manejando en la base de datos el tema gerente-sede es recomendable permitirle al super crear sedes en un estado inicial para comenzar la empresa

**Comment by 1625690** [comment]
En estos momentos que tipos de usuario pueden crear sedes?

**Comment by Shinku24** [comment]
Únicamente el gerente, la propuesta se realiza con el fin de crear la sede inicial

**Comment by 1625690** [comment]
Yo opino que al inicializar el programa apenas se cree el súper usuario,
deba crearse una sede principal por obligación, no se si así es el manejo
que pensabas darle

**Comment by Shinku24** [comment]
La creación del super usuario debería implementarse cuando se crean las tablas, amenos que se quiera hacer un sql solo para ello

por el lado de las sedes estoy bien con la elección que se llegue, pero necesito la info para modf las HU y la interfaz

**Comment by Shinku24** [comment]
El resto que opina al respecto: Lo que comenté al inicio o la propuesta de perafan? cual es mas viable?

**Comment by Valeriarm** [comment]
lo siento, acabo de ver el email de esto. 
yo pienso que lo que dice perafan es valido, al igual que el super usuario se puede crear la sede default, ya las siguiente sedes serán creadas con el gerente. Además esta solución es mas sencilla en cuanto a interfaz que hacer que los Super puedan crear las sedes

**Comment by Shinku24** [comment]
ok, entonces supongo que vamos con esa idea

**Comment by 1625690** [comment]
Me parece la más indicada y práctica
